# Generated by Django 5.2 on 2025-05-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('meat', 'Meat'), ('drinks', 'Drinks'), ('sauces', 'Sauces'), ('sides', 'Sides'), ('utensils', 'Utensils')], max_length=20)),
                ('item', models.CharField(max_length=20)),
                ('quantity', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
